schema = "https://raw.githubusercontent.com/triesap/eqm/master/schemas/v1/manifest/capability.schema.json"
id = "account.create"
title = "Create account"
status = "active"
owners = ["owner://team/identity_product"]
