[package]
name = "eqm_test_support"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
readme.workspace = true
repository.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
eqm_domain.workspace = true
eqm_engine.workspace = true
eqm_manifest.workspace = true
eqm_protocol.workspace = true
eqm_runner.workspace = true

[lints]
workspace = true
