[package]
name = "eqm"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
readme.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
chrono.workspace = true
eqm_domain.workspace = true
eqm_engine.workspace = true
eqm_manifest.workspace = true
eqm_mcp.workspace = true
eqm_protocol.workspace = true
eqm_runner.workspace = true
serde_json.workspace = true
tempfile.workspace = true

[lints]
workspace = true
